# Eevee Clues - Ren'Py options
define config.name = "Eevee Clues"
define config.version = "0.1"
define gui.show_name = True
define config.has_sound = True
define config.has_music = True
define config.has_voice = False
define config.save_directory = "EeveeClues-1637298379"
define config.enter_transition = Dissolve(0.2)
define config.exit_transition = Dissolve(0.2)
define config.after_load_transition = None
define config.end_game_transition = None
define config.main_menu_music = None
define config.game_main_transition = None
define config.window = "auto"
define config.window_show_transition = Dissolve(0.2)
define config.window_hide_transition = Dissolve(0.2)
define config.thumbnail_width = 256
define config.thumbnail_height = 144
define config.default_text_cps = 0
define config.allow_skipping = True
define config.has_autosave = False
define config.autosave_on_quit = False
define config.autosave_on_choice = False
define config.layers = ['master', 'transient', 'screens', 'overlay']
define config.image_cache_size = 64
define config.predict_statements = 10
define config.menu_clear_layers = ['master']
define config.script_version = (8, 0, 0)
